added the stylings for the web version of the page
Trust-007/My-Portfolio-Website pull request #6
Opened 2022-09-28 17:07 UTC by Trust-007

Added media query to css for the web version of the page

2022-09-28 18:51 UTC, mckent05 requested changes
Hi @Trust-007, 

# STATUS: CHANGES REQUIRED ♻️ ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/192864096-5c7548bd-16ac-47e8-a159-4b215b4f72df.gif)

## Highlights
- Linters are passing ✔️ ✔️ 
- PR title and summary are descriptive 💯 💯 
- Your portfolios gradually coming together and starting to look complete 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 18:51 UTC, mckent05 commented on index.css
> +  }
- Nice work you have done so far 👍 , but there are still some small differences between the Figma template and your design 😄. the width of your navbar doesn't exactly match the design. Please try to fix this. Know that replicating the exact specifications gives confidence to recruiters in your ability to design the exact webpage they'll require 🙏 

- Please also note that the background images does not exactly match what is in the figma template, please try to fix that 🙏 
Your project looks like this:
- Please pay attention to the margin difference between your logo and the left border of the site and also the margin difference between the nav links and the right border of the site.
![figma 1 desktop project](https://user-images.githubusercontent.com/73607512/192858087-fcdce8a5-0789-4557-8508-3e13953ec8c5.PNG)

Figma template:
![figma 1 desktop figma](https://user-images.githubusercontent.com/73607512/192858210-4d1713aa-dbe1-4d14-8252-29398dc9beaf.PNG)

2022-09-28 18:51 UTC, mckent05 commented on index.css
> +  }
- Nice work you have done so far 👍 , but there are still some small differences between the Figma template and your design 😄. the width of your project cards doesn't exactly match the design. Please try to fix this. Know that replicating the exact specifications gives confidence to recruiters in your ability to design the exact webpage they'll require 🙏

Your project looks like this:

   - Please pay attention to the width of each of your project cards 🙏. The width in the Figma design takes a little bit more space than you have implemented in your design. I suggest you look into fixing this 👍 
 ![work card figma](https://user-images.githubusercontent.com/73607512/192861749-7b3cec64-fd42-4314-9cea-6c56de4db92a.PNG)

Figma template-
![work card student](https://user-images.githubusercontent.com/73607512/192861468-76365269-b5bd-4e78-baef-6c838f26660f.PNG)

2022-09-28 18:51 UTC, mckent05 commented on index.css
> +
- Please also note that the background images in your contact section does not exactly match what is in the figma template, please try to fix that 🙏

Your project looks like this:
![contact figma 1 temlate](https://user-images.githubusercontent.com/73607512/192862962-98e688e4-1c94-4d74-a67c-b758fdb9e278.PNG)

Figma template-
![figma desktop contact](https://user-images.githubusercontent.com/73607512/192863607-bd1018bd-c6c8-468f-a625-4f64df2183c9.PNG)

2022-09-29 10:04 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ ✔️ 

Hi @Trust-007, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Github flow ✔️ 
- [ ] Good commit messages ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 10:35 UTC, merged